# installs docker on Ubuntu 14.04. hosts
---
- name: Update Apt
  apt: name=docker.io update_cache=yes

- name: Link docker
  file: >
    dest=/usr/local/bin/docker
    src=/usr/bin/docker.io
    state=link
