# this file is for running on an individual host: instance1
# this was created just to try it out on one server
- name: Configure webserver with nginx
  hosts: instance1
  sudo: True
  tasks:
    - name: install nginx
      apt: name=nginx update_cache=yes
    - name: copy nginx config file
      copy: src=files/nginx.conf dest=/etc/nginx/sites-available/default 
      notify: restart nginx
    - name: enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link
    - name: copy index.html
      copy: src=files/index.html dest=/usr/share/nginx/html/index.html mode=0644
      notify: restart nginx
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
